RULE_SOURCE_MAPPINGS = {
    "device": {
        "manufacturer": "brand",
        "brand": "brand",
        "brand_name": "brand",
        "maker": "brand",
        "vendor": "brand",
        "device_model": "model",
        "model": "model",
        "model_name": "model",
        "product_name": "model",
        "ram": "ram_gb",
        "memory_ram": "ram_gb",
        "memory": "ram_gb",
        "storage": "storage_gb",
        "internal_storage": "storage_gb",
        "capacity": "storage_gb",
        "rom": "storage_gb",
        "price": "price_eur",
        "price_eur": "price_eur",
        "cost": "price_eur",
    },
    "mobile_plan": {
        "carrier": "provider",
        "operator": "provider",
        "provider": "provider",
        "company": "provider",
        "tariff_name": "tariff_name",
        "plan": "tariff_name",
        "plan_name": "tariff_name",
        "tariff": "tariff_name",
        "price": "price_eur_per_month",
        "monthly_fee": "price_eur_per_month",
        "monthly_price": "price_eur_per_month",
        "fee": "price_eur_per_month",
        "data_volume": "data_gb",
        "data_limit": "data_gb",
        "data": "data_gb",
        "data_gb": "data_gb",
        "internet": "data_gb",
        "allowance": "data_gb",
        "contract_length": "contract_months",
        "duration": "contract_months",
        "term": "contract_months",
        "commitment": "contract_months",
        "contract": "contract_months",
    },
}


SEMANTIC_SOURCE_MAPPINGS = {
    "device": {
        **RULE_SOURCE_MAPPINGS["device"],
        "device_info_maker": "brand",
        "device_brand_name": "brand",
        "phone": "model",
        "product": "model",
        "name": "model",
        "device_info_name": "model",
        "device_model_name": "model",
        "ram_memory": "ram_gb",
        "hardware_specs_memory": "ram_gb",
        "storage_capacity": "storage_gb",
        "disk": "storage_gb",
        "amount": "price_eur",
        "price_tag": "price_eur",
        "pricing_amount": "price_eur",
    },
    "mobile_plan": {
        **RULE_SOURCE_MAPPINGS["mobile_plan"],
        "provider_name": "provider",
        "name": "provider",
        "carrier_info_name": "provider",
        "title": "tariff_name",
        "offer": "tariff_name",
        "tariff_details_title": "tariff_name",
        "price_info": "price_eur_per_month",
        "tariff_details_price_info": "price_eur_per_month",
        "internet_data": "data_gb",
        "internet_package": "data_gb",
        "data_package": "data_gb",
        "tariff_details_internet_package": "data_gb",
        "contract_type": "contract_months",
        "metadata_contract": "contract_months",
    },
}
